name: zahid_bruk_web
description: A web app that uses AngularDart
version: 0.0.1

environment:
  sdk: '^1.8.0'

dependencies:
  angular2: ^3.0.0
  lab_rat_wp_api: "^1.0.0"
  gtag_analytics: "^0.1.5"

  

dev_dependencies:
  angular_test: ^1.0.0-beta+2
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  test: ^0.12.21

transformers:
- angular2:
    entry_points: web/main.dart
- angular2/transform/reflection_remover:
    $include: 
    - test/**_test.dart
    - web/main.dart
    - package:*
- test/pub_serve:
    $include: test/**_test.dart
- dart_to_js_script_rewriter
- $dart2js:
    commandLineOptions: [--trust-type-annotations]
    # commandLineOptions: [--trust-type-annotations, --trust-primitives]


web:
  compiler:
    debug: dartdevc